[package]
name = "agent_matrix"
version = "1.1.0"
edition = "2021"
[dependencies]
ratatui = "0.26"
tokio = { version = "1", features = ["full"] }
aes-gcm = "0.10"
blake3 = "1.5"
kyberlib = "0.0.6"  # Quantum KEM stub
fuzzy-matcher = "0.3"
rand = "0.8"